version: '3'
services:
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: "abc123"
            MYSQL_USER: 'test'
            MYSQL_PASS: 'yourpassword'
        image: "docker.io/mysql:latest" 
        restart: always
        ports:
            - "3306:3306"
        # volumes:
        #     - "./db:/var/lib/mysql"
        #     - "./conf/my.cnf:/etc/my.cnf"
        #     - "./init:/docker-entrypoint-initdb.d/"
